on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Release qyoobs-vnc
    runs-on: ubuntu-latest
    container: docker.io/library/fedora:40
    steps:
      - uses: actions/checkout@v3
      - run: sudo dnf install -y rustup libX11-devel libXinerama-devel gcc make cmake automake gh
      - run: |
          rustup-init -y
          echo "$HOME/.cargo/bin" >>"$GITHUB_PATH"
      - run: cargo install cargo-generate-rpm
      - run: cargo build --release
      - run: cargo generate-rpm

      - name: Compute checksums
        id: checksums
        # The files listed on this line must be identical to the files uploaded
        # in the last step.
        run: sha256sum qyoobs-vnc*.rpm >| qyoobs-vnc.$(date +%s)-$(git rev-parse --short=8 HEAD).checksums.txt

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="$tag" --generate-notes
          gh release upload "$tag" --repo="$GITHUB_REPOSITORY" target/generate-rpm/qyoobs-vnc*.rpm qyoobs-vnc*.checksums.txt
